### ISSUE TITLE
Unable to update prosemirror-transform to v1.4.2

### ISSUE THREAD

**Issue by ocavue** [remirror/remirror#1632]
### Summary

I tried to update `prosemirror-transform` in `remirror` from `1.3.3` to `1.4.2`, but some unit tests fail after updating. 

I have not debugged this yet, just record it first. 

```
$ cd remirror
$ npm-check-updates --deep '/prosemirror-transform/' -u 
$ pnpm install 
$ pnpm test packages/remirror__extension-link/__tests__/link-extension.spec.ts


  ● autolinking › can auto link

    expect(received).toEqualRemirrorDocument(expected)

    Expected JSON value of document to equal:
    {"content": [{"content": [{"marks": [{"attrs": {"auto": true, "href": "//test.co", "target": null}, "type": "link"}], "text": "test.co", "type": "text"}], "type": "paragraph"}], "type": "doc"}
    Actual JSON:
      {"content": [{"content": [{"text": "test.co", "type": "text"}], "type": "paragraph"}], "type": "doc"}

    Difference:

    - Expected
    + Received

    @@ -1,20 +1,10 @@
      Object {
        "content": Array [
          Object {
            "content": Array [
              Object {
    -           "marks": Array [
    -             Object {
    -               "attrs": Object {
    -                 "auto": true,
    -                 "href": "//test.co",
    -                 "target": null,
    -               },
    -               "type": "link",
    -             },
    -           ],
                "text": "test.co",
                "type": "text",
              },
            ],
            "type": "paragraph",

      520 |     editor.add(doc(p('<cursor>'))).insertText('test.co');
      521 |
    > 522 |     expect(editor.doc).toEqualRemirrorDocument(
          |                        ^
      523 |       doc(p(link({ auto: true, href: '//test.co' })('test.co'))),
      524 |     );
      525 |

      at Object.<anonymous> (packages/remirror__extension-link/__tests__/link-extension.spec.ts:522:24)
      at TestScheduler.scheduleTests (node_modules/.pnpm/@jest+core@27.3.1/node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/.pnpm/@jest+core@27.3.1/node_modules/@jest/core/build/runJest.js:401:19)
      at _run10000 (node_modules/.pnpm/@jest+core@27.3.1/node_modules/@jest/core/build/cli/index.js:320:7)
      at runCLI (node_modules/.pnpm/@jest+core@27.3.1/node_modules/@jest/core/build/cli/index.js:173:3)


```

**Comment by ocavue** [comment]
Fixed in #1651
