### ISSUE TITLE
addYouTubeVideo.isEnabled() throws error

### ISSUE THREAD

**Issue by ronnyroeller** [remirror/remirror#768]
### Summary

I want to check if the editor should offer to insert a youtube video. For this, I call `commands.addYouTubeVideo.isEnabled()`. Doing so, throws this errors:
```
TypeError: Cannot read property 'video' of undefined
    at createYouTubeUrl (https://qmuwc.csb.app/node_modules/@remirror/preset-embed/dist/preset-embed.browser.esm.js:162:25)
    at IframeExtension.eval [as addYouTubeVideo] (https://qmuwc.csb.app/node_modules/@remirror/preset-embed/dist/preset-embed.browser.esm.js:52:14)
    at addYouTubeVideo (https://qmuwc.csb.app/node_modules/@remirror/preset-embed/dist/preset-embed.browser.esm.js:139:42)
    at Function.eval [as isEnabled] (https://qmuwc.csb.app/node_modules/@remirror/core/dist/core.browser.esm.js:1406:14)
```

### Steps to reproduce

1. Open reproduction case on codesandbox: https://codesandbox.io/s/focused-hawking-qmuwc?file=/src/App.js:385-410
2. Check console for error

### Expected results

`isEnabled()` returns boolean.

### Actual results

Throws error

**Comment by ifiokjr** [comment]
Interestingly, this issue raises a much-needed enhancement.

The reason it's failing is that the `addYoutube` command expected an object with the `video` property. There are two ways of dealing with this. Either require the same arguments for the `isEnabled` function as the actual command, or, make sure the function can handle `isEnabled` without requiring access to the first parameter. 

Either way, I'll need to improve the types that are generated.
