### ISSUE TITLE
pnpm run docs:dev throws an error 

### ISSUE THREAD

**Issue by ocavue** [remirror/remirror#858]
### Summary

`docs:dev` throws an error with `Error: ENAMETOOLONG: name too long`

OS: macOS 10.15.7
Node: 15.5.1

### Steps to reproduce

Run `pnpm run docs:dev` in `beta` branch.

### Expected results

no error.

### Actual results

N/A

### Possible Solution

N/A

### Screenshot(s)
 
```shell
$ pnpm run docs:dev    

> remirror-monorepo@ docs:dev /Users/ocavue/code/github/remirror_beta
> cd website && pnpm start


> website@0.0.0 start /Users/ocavue/code/github/remirror_beta/website
> docusaurus start

Starting the development server...
Info: Loaded plugin typedoc-plugin-markdown
Warning: Provided entry point ../deprecated/remirror__core-extensions/src/index.ts,../deprecated/remirror__editor-markdown/src/index.ts,../deprecated/remirror__editor-social/src/index.ts,../deprecated/remirror__editor-wysiwyg/src/index.ts,../deprecated/remirror__extension-auto-link/src/index.ts,../deprecated/remirror__extension-base-keymap/src/index.ts,../deprecated/remirror__extension-enhanced-link/src/index.ts,../deprecated/remirror__preset-social/src/index.ts,../deprecated/remirror__react-node-view/src/index.ts,../deprecated/remirror__react-portals/src/index.ts,../deprecated/remirror__react-social/src/index.ts,../deprecated/remirror__react-wysiwyg/src/index.ts,../deprecated/remirror__showcase/src/index.ts,../deprecated/remirror__ui/src/index.ts,../deprecated/remirror__ui-a11y-status/src/index.ts,../deprecated/remirror__ui-buttons/src/index.ts,../deprecated/remirror__ui-dropdown/src/index.ts,../deprecated/remirror__ui-icons/src/index.ts,../deprecated/remirror__ui-menus/src/index.ts,../deprecated/remirror__ui-modal/src/index.ts,../deprecated/remirror__ui-text/src/index.ts,../examples/storybook-react/src/index.ts,../examples/with-next/src/index.ts,../examples/with-react-native/src/index.ts,../packages/a11y-status/src/index.ts,../packages/create-context-state/src/index.ts,../packages/jest-prosemirror/src/index.ts,../packages/jest-remirror/src/index.ts,../packages/multishift/src/index.ts,../packages/prosemirror-paste-rules/src/index.ts,../packages/prosemirror-suggest/src/index.ts,../packages/prosemirror-trailing-node/src/index.ts,../packages/remirror/src/index.ts,../packages/remirror__cli/src/index.ts,../packages/remirror__core/src/index.ts,../packages/remirror__core-constants/src/index.ts,../packages/remirror__core-helpers/src/index.ts,../packages/remirror__core-types/src/index.ts,../packages/remirror__core-utils/src/index.ts,../packages/remirror__dev/src/index.ts,../packages/remirror__dom/src/index.ts,../packages/remirror__es-module-shims/src/index.ts,../packages/remirror__extension-annotation/src/index.ts,../packages/remirror__extension-bidi/src/index.ts,../packages/remirror__extension-blockquote/src/index.ts,../packages/remirror__extension-bold/src/index.ts,../packages/remirror__extension-callout/src/index.ts,../packages/remirror__extension-code/src/index.ts,../packages/remirror__extension-code-block/src/index.ts,../packages/remirror__extension-codemirror5/src/index.ts,../packages/remirror__extension-collaboration/src/index.ts,../packages/remirror__extension-columns/src/index.ts,../packages/remirror__extension-diff/src/index.ts,../packages/remirror__extension-doc/src/index.ts,../packages/remirror__extension-drop-cursor/src/index.ts,../packages/remirror__extension-embed/src/index.ts,../packages/remirror__extension-emoji/src/index.ts,../packages/remirror__extension-epic-mode/src/index.ts,../packages/remirror__extension-events/src/index.ts,../packages/remirror__extension-font-family/src/index.ts,../packages/remirror__extension-font-size/src/index.ts,../packages/remirror__extension-gap-cursor/src/index.ts,../packages/remirror__extension-hard-break/src/index.ts,../packages/remirror__extension-heading/src/index.ts,../packages/remirror__extension-history/src/index.ts,../packages/remirror__extension-horizontal-rule/src/index.ts,../packages/remirror__extension-image/src/index.ts,../packages/remirror__extension-italic/src/index.ts,../packages/remirror__extension-link/src/index.ts,../packages/remirror__extension-list/src/index.ts,../packages/remirror__extension-markdown/src/index.ts,../packages/remirror__extension-mention/src/index.ts,../packages/remirror__extension-mention-atom/src/index.ts,../packages/remirror__extension-node-formatting/src/index.ts,../packages/remirror__extension-paragraph/src/index.ts,../packages/remirror__extension-placeholder/src/index.ts,../packages/remirror__extension-positioner/src/index.ts,../packages/remirror__extension-react-component/src/index.ts,../packages/remirror__extension-react-native-bridge/src/index.ts,../packages/remirror__extension-react-ssr/src/index.ts,../packages/remirror__extension-search/src/index.ts,../packages/remirror__extension-strike/src/index.ts,../packages/remirror__extension-sub/src/index.ts,../packages/remirror__extension-sup/src/index.ts,../packages/remirror__extension-tables/src/index.ts,../packages/remirror__extension-text/src/index.ts,../packages/remirror__extension-text-case/src/index.ts,../packages/remirror__extension-text-color/src/index.ts,../packages/remirror__extension-text-highlight/src/index.ts,../packages/remirror__extension-trailing-node/src/index.ts,../packages/remirror__extension-underline/src/index.ts,../packages/remirror__extension-whitespace/src/index.ts,../packages/remirror__extension-yjs/src/index.ts,../packages/remirror__i18n/src/index.ts,../packages/remirror__icons/src/index.ts,../packages/remirror__lit/src/index.ts,../packages/remirror__lit-components/src/index.ts,../packages/remirror__messages/src/index.ts,../packages/remirror__playground/src/index.ts,../packages/remirror__pm/src/index.ts,../packages/remirror__preset-core/src/index.ts,../packages/remirror__preset-formatting/src/index.ts,../packages/remirror__preset-react/src/index.ts,../packages/remirror__preset-wysiwyg/src/index.ts,../packages/remirror__react/src/index.ts,../packages/remirror__react-components/src/index.ts,../packages/remirror__react-core/src/index.ts,../packages/remirror__react-debugger/src/index.ts,../packages/remirror__react-hooks/src/index.ts,../packages/remirror__react-native/src/index.ts,../packages/remirror__react-renderer/src/index.ts,../packages/remirror__react-ssr/src/index.ts,../packages/remirror__react-utils/src/index.ts,../packages/remirror__styles/src/index.ts,../packages/remirror__svelte/src/index.ts,../packages/remirror__theme/src/index.ts,../packages/test-keyboard/src/index.ts,../packages/testing/src/index.ts,../support/src/index.ts,../support/actions/src/index.ts,../support/scripts/src/index.ts,../support/templates/extension-template/src/index.ts,../support/templates/minimal-template/src/index.ts,../support/templates/preset-template/src/index.ts,src/index.ts does not exist and will not be included in the docs.
node:fs:1044
  handleErrorFromBinding(ctx);
  ^

Error: ENAMETOOLONG: name too long, scandir '/Users/ocavue/code/github/remirror_beta/deprecated/remirror__core-extensions/src/index.ts,../deprecated/remirror__editor-markdown/src/index.ts,../deprecated/remirror__editor-social/src/index.ts,../deprecated/remirror__editor-wysiwyg/src/index.ts,../deprecated/remirror__extension-auto-link/src/index.ts,../deprecated/remirror__extension-base-keymap/src/index.ts,../deprecated/remirror__extension-enhanced-link/src/index.ts,../deprecated/remirror__preset-social/src/index.ts,../deprecated/remirror__react-node-view/src/index.ts,../deprecated/remirror__react-portals/src/index.ts,../deprecated/remirror__react-social/src/index.ts,../deprecated/remirror__react-wysiwyg/src/index.ts,../deprecated/remirror__showcase/src/index.ts,../deprecated/remirror__ui/src/index.ts,../deprecated/remirror__ui-a11y-status/src/index.ts,../deprecated/remirror__ui-buttons/src/index.ts,../deprecated/remirror__ui-dropdown/src/index.ts,../deprecated/remirror__ui-icons/src/index.ts,../deprecated/remirror__ui-menus/src/index.ts,../deprecated/remirror__ui-modal/src/index.ts,../deprecated/remirror__ui-text/src/index.ts,../examples/storybook-react/src/index.ts,../examples/with-next/src/index.ts,../examples/with-react-native/src/index.ts,../packages/a11y-status/src/index.ts,../packages/create-context-state/src/index.ts,../packages/jest-prosemirror/src/index.ts,../packages/jest-remirror/src/index.ts,../packages/multishift/src/index.ts,../packages/prosemirror-paste-rules/src/index.ts,../packages/prosemirror-suggest/src/index.ts,../packages/prosemirror-trailing-node/src/index.ts,../packages/remirror/src/index.ts,../packages/remirror__cli/src/index.ts,../packages/remirror__core/src/index.ts,../packages/remirror__core-constants/src/index.ts,../packages/remirror__core-helpers/src/index.ts,../packages/remirror__core-types/src/index.ts,../packages/remirror__core-utils/src/index.ts,../packages/remirror__dev/src/index.ts,../packages/remirror__dom/src/index.ts,../packages/remirror__es-module-shims/src/index.ts,../packages/remirror__extension-annotation/src/index.ts,../packages/remirror__extension-bidi/src/index.ts,../packages/remirror__extension-blockquote/src/index.ts,../packages/remirror__extension-bold/src/index.ts,../packages/remirror__extension-callout/src/index.ts,../packages/remirror__extension-code/src/index.ts,../packages/remirror__extension-code-block/src/index.ts,../packages/remirror__extension-codemirror5/src/index.ts,../packages/remirror__extension-collaboration/src/index.ts,../packages/remirror__extension-columns/src/index.ts,../packages/remirror__extension-diff/src/index.ts,../packages/remirror__extension-doc/src/index.ts,../packages/remirror__extension-drop-cursor/src/index.ts,../packages/remirror__extension-embed/src/index.ts,../packages/remirror__extension-emoji/src/index.ts,../packages/remirror__extension-epic-mode/src/index.ts,../packages/remirror__extension-events/src/index.ts,../packages/remirror__extension-font-family/src/index.ts,../packages/remirror__extension-font-size/src/index.ts,../packages/remirror__extension-gap-cursor/src/index.ts,../packages/remirror__extension-hard-break/src/index.ts,../packages/remirror__extension-heading/src/index.ts,../packages/remirror__extension-history/src/index.ts,../packages/remirror__extension-horizontal-rule/src/index.ts,../packages/remirror__extension-image/src/index.ts,../packages/remirror__extension-italic/src/index.ts,../packages/remirror__extension-link/src/index.ts,../packages/remirror__extension-list/src/index.ts,../packages/remirror__extension-markdown/src/index.ts,../packages/remirror__extension-mention/src/index.ts,../packages/remirror__extension-mention-atom/src/index.ts,../packages/remirror__extension-node-formatting/src/index.ts,../packages/remirror__extension-paragraph/src/index.ts,../packages/remirror__extension-placeholder/src/index.ts,../packages/remirror__extension-positioner/src/index.ts,../packages/remirror__extension-react-component/src/index.ts,../packages/remirror__extension-react-native-bridge/src/index.ts,../packages/remirror__extension-react-ssr/src/index.ts,../packages/remirror__extension-search/src/index.ts,../packages/remirror__extension-strike/src/index.ts,../packages/remirror__extension-sub/src/index.ts,../packages/remirror__extension-sup/src/index.ts,../packages/remirror__extension-tables/src/index.ts,../packages/remirror__extension-text/src/index.ts,../packages/remirror__extension-text-case/src/index.ts,../packages/remirror__extension-text-color/src/index.ts,../packages/remirror__extension-text-highlight/src/index.ts,../packages/remirror__extension-trailing-node/src/index.ts,../packages/remirror__extension-underline/src/index.ts,../packages/remirror__extension-whitespace/src/index.ts,../packages/remirror__extension-yjs/src/index.ts,../packages/remirror__i18n/src/index.ts,../packages/remirror__icons/src/index.ts,../packages/remirror__lit/src/index.ts,../packages/remirror__lit-components/src/index.ts,../packages/remirror__messages/src/index.ts,../packages/remirror__playground/src/index.ts,../packages/remirror__pm/src/index.ts,../packages/remirror__preset-core/src/index.ts,../packages/remirror__preset-formatting/src/index.ts,../packages/remirror__preset-react/src/index.ts,../packages/remirror__preset-wysiwyg/src/index.ts,../packages/remirror__react/src/index.ts,../packages/remirror__react-components/src/index.ts,../packages/remirror__react-core/src/index.ts,../packages/remirror__react-debugger/src/index.ts,../packages/remirror__react-hooks/src/index.ts,../packages/remirror__react-native/src/index.ts,../packages/remirror__react-renderer/src/index.ts,../packages/remirror__react-ssr/src/index.ts,../packages/remirror__react-utils/src/index.ts,../packages/remirror__styles/src/index.ts,../packages/remirror__svelte/src/index.ts,../packages/remirror__theme/src/index.ts,../packages/test-keyboard/src/index.ts,../packages/testing/src/index.ts,../support/src/index.ts,../support/actions/src/index.ts,../support/scripts/src/index.ts,../support/templates/extension-template/src/index.ts,../support/templates/minimal-template/src/index.ts,../support/templates/preset-template/src/index.ts,src'
    at Object.readdirSync (node:fs:1044:3)
    at PackagePlugin.onBegin (/Users/ocavue/code/github/remirror_beta/node_modules/.pnpm/typedoc@0.20.20/node_modules/typedoc/dist/lib/converter/plugins/PackagePlugin.js:51:16)
    at triggerEvents (/Users/ocavue/code/github/remirror_beta/node_modules/.pnpm/typedoc@0.20.20/node_modules/typedoc/dist/lib/utils/events.js:173:43)
    at triggerApi (/Users/ocavue/code/github/remirror_beta/node_modules/.pnpm/typedoc@0.20.20/node_modules/typedoc/dist/lib/utils/events.js:149:13)
    at eventsApi (/Users/ocavue/code/github/remirror_beta/node_modules/.pnpm/typedoc@0.20.20/node_modules/typedoc/dist/lib/utils/events.js:42:18)
    at Converter.trigger (/Users/ocavue/code/github/remirror_beta/node_modules/.pnpm/typedoc@0.20.20/node_modules/typedoc/dist/lib/utils/events.js:371:13)
    at Converter.convert (/Users/ocavue/code/github/remirror_beta/node_modules/.pnpm/typedoc@0.20.20/node_modules/typedoc/dist/lib/converter/converter.js:42:14)
    at Application.convert (/Users/ocavue/code/github/remirror_beta/node_modules/.pnpm/typedoc@0.20.20/node_modules/typedoc/dist/lib/application.js:157:31)
    at pluginDocusaurus (/Users/ocavue/code/github/remirror_beta/node_modules/.pnpm/docusaurus-plugin-typedoc@0.9.0_63da3c7c2c53de10c4225f8689710554/node_modules/docusaurus-plugin-typedoc/dist/plugin.js:30:33)
    at /Users/ocavue/code/github/remirror_beta/node_modules/.pnpm/@docusaurus/core@2.0.0-alpha.70_react-dom@17.0.1+react@17.0.1/node_modules/@docusaurus/core/lib/server/plugins/init.js:71:48
    at Array.map (<anonymous>)
    at Object.initPlugins [as default] (/Users/ocavue/code/github/remirror_beta/node_modules/.pnpm/@docusaurus/core@2.0.0-alpha.70_react-dom@17.0.1+react@17.0.1/node_modules/@docusaurus/core/lib/server/plugins/init.js:27:10)
    at Object.loadPlugins (/Users/ocavue/code/github/remirror_beta/node_modules/.pnpm/@docusaurus/core@2.0.0-alpha.70_react-dom@17.0.1+react@17.0.1/node_modules/@docusaurus/core/lib/server/plugins/index.js:50:35)
    at Object.load (/Users/ocavue/code/github/remirror_beta/node_modules/.pnpm/@docusaurus/core@2.0.0-alpha.70_react-dom@17.0.1+react@17.0.1/node_modules/@docusaurus/core/lib/server/index.js:108:98)
    at async start (/Users/ocavue/code/github/remirror_beta/node_modules/.pnpm/@docusaurus/core@2.0.0-alpha.70_react-dom@17.0.1+react@17.0.1/node_modules/@docusaurus/core/lib/commands/start.js:43:19) {
  errno: -63,
  syscall: 'scandir',
  code: 'ENAMETOOLONG',
  path: '/Users/ocavue/code/github/remirror_beta/deprecated/remirror__core-extensions/src/index.ts,../deprecated/remirror__editor-markdown/src/index.ts,../deprecated/remirror__editor-social/src/index.ts,../deprecated/remirror__editor-wysiwyg/src/index.ts,../deprecated/remirror__extension-auto-link/src/index.ts,../deprecated/remirror__extension-base-keymap/src/index.ts,../deprecated/remirror__extension-enhanced-link/src/index.ts,../deprecated/remirror__preset-social/src/index.ts,../deprecated/remirror__react-node-view/src/index.ts,../deprecated/remirror__react-portals/src/index.ts,../deprecated/remirror__react-social/src/index.ts,../deprecated/remirror__react-wysiwyg/src/index.ts,../deprecated/remirror__showcase/src/index.ts,../deprecated/remirror__ui/src/index.ts,../deprecated/remirror__ui-a11y-status/src/index.ts,../deprecated/remirror__ui-buttons/src/index.ts,../deprecated/remirror__ui-dropdown/src/index.ts,../deprecated/remirror__ui-icons/src/index.ts,../deprecated/remirror__ui-menus/src/index.ts,../deprecated/remirror__ui-modal/src/index.ts,../deprecated/remirror__ui-text/src/index.ts,../examples/storybook-react/src/index.ts,../examples/with-next/src/index.ts,../examples/with-react-native/src/index.ts,../packages/a11y-status/src/index.ts,../packages/create-context-state/src/index.ts,../packages/jest-prosemirror/src/index.ts,../packages/jest-remirror/src/index.ts,../packages/multishift/src/index.ts,../packages/prosemirror-paste-rules/src/index.ts,../packages/prosemirror-suggest/src/index.ts,../packages/prosemirror-trailing-node/src/index.ts,../packages/remirror/src/index.ts,../packages/remirror__cli/src/index.ts,../packages/remirror__core/src/index.ts,../packages/remirror__core-constants/src/index.ts,../packages/remirror__core-helpers/src/index.ts,../packages/remirror__core-types/src/index.ts,../packages/remirror__core-utils/src/index.ts,../packages/remirror__dev/src/index.ts,../packages/remirror__dom/src/index.ts,../packages/remirror__es-module-shims/src/index.ts,../packages/remirror__extension-annotation/src/index.ts,../packages/remirror__extension-bidi/src/index.ts,../packages/remirror__extension-blockquote/src/index.ts,../packages/remirror__extension-bold/src/index.ts,../packages/remirror__extension-callout/src/index.ts,../packages/remirror__extension-code/src/index.ts,../packages/remirror__extension-code-block/src/index.ts,../packages/remirror__extension-codemirror5/src/index.ts,../packages/remirror__extension-collaboration/src/index.ts,../packages/remirror__extension-columns/src/index.ts,../packages/remirror__extension-diff/src/index.ts,../packages/remirror__extension-doc/src/index.ts,../packages/remirror__extension-drop-cursor/src/index.ts,../packages/remirror__extension-embed/src/index.ts,../packages/remirror__extension-emoji/src/index.ts,../packages/remirror__extension-epic-mode/src/index.ts,../packages/remirror__extension-events/src/index.ts,../packages/remirror__extension-font-family/src/index.ts,../packages/remirror__extension-font-size/src/index.ts,../packages/remirror__extension-gap-cursor/src/index.ts,../packages/remirror__extension-hard-break/src/index.ts,../packages/remirror__extension-heading/src/index.ts,../packages/remirror__extension-history/src/index.ts,../packages/remirror__extension-horizontal-rule/src/index.ts,../packages/remirror__extension-image/src/index.ts,../packages/remirror__extension-italic/src/index.ts,../packages/remirror__extension-link/src/index.ts,../packages/remirror__extension-list/src/index.ts,../packages/remirror__extension-markdown/src/index.ts,../packages/remirror__extension-mention/src/index.ts,../packages/remirror__extension-mention-atom/src/index.ts,../packages/remirror__extension-node-formatting/src/index.ts,../packages/remirror__extension-paragraph/src/index.ts,../packages/remirror__extension-placeholder/src/index.ts,../packages/remirror__extension-positioner/src/index.ts,../packages/remirror__extension-react-component/src/index.ts,../packages/remirror__extension-react-native-bridge/src/index.ts,../packages/remirror__extension-react-ssr/src/index.ts,../packages/remirror__extension-search/src/index.ts,../packages/remirror__extension-strike/src/index.ts,../packages/remirror__extension-sub/src/index.ts,../packages/remirror__extension-sup/src/index.ts,../packages/remirror__extension-tables/src/index.ts,../packages/remirror__extension-text/src/index.ts,../packages/remirror__extension-text-case/src/index.ts,../packages/remirror__extension-text-color/src/index.ts,../packages/remirror__extension-text-highlight/src/index.ts,../packages/remirror__extension-trailing-node/src/index.ts,../packages/remirror__extension-underline/src/index.ts,../packages/remirror__extension-whitespace/src/index.ts,../packages/remirror__extension-yjs/src/index.ts,../packages/remirror__i18n/src/index.ts,../packages/remirror__icons/src/index.ts,../packages/remirror__lit/src/index.ts,../packages/remirror__lit-components/src/index.ts,../packages/remirror__messages/src/index.ts,../packages/remirror__playground/src/index.ts,../packages/remirror__pm/src/index.ts,../packages/remirror__preset-core/src/index.ts,../packages/remirror__preset-formatting/src/index.ts,../packages/remirror__preset-react/src/index.ts,../packages/remirror__preset-wysiwyg/src/index.ts,../packages/remirror__react/src/index.ts,../packages/remirror__react-components/src/index.ts,../packages/remirror__react-core/src/index.ts,../packages/remirror__react-debugger/src/index.ts,../packages/remirror__react-hooks/src/index.ts,../packages/remirror__react-native/src/index.ts,../packages/remirror__react-renderer/src/index.ts,../packages/remirror__react-ssr/src/index.ts,../packages/remirror__react-utils/src/index.ts,../packages/remirror__styles/src/index.ts,../packages/remirror__svelte/src/index.ts,../packages/remirror__theme/src/index.ts,../packages/test-keyboard/src/index.ts,../packages/testing/src/index.ts,../support/src/index.ts,../support/actions/src/index.ts,../support/scripts/src/index.ts,../support/templates/extension-template/src/index.ts,../support/templates/minimal-template/src/index.ts,../support/templates/preset-template/src/index.ts,src'
}
 ERROR  Command failed with exit code 1.
 ERROR  Command failed with exit code 1.
```

**Comment by ifiokjr** [comment]
I'll start looking at this today, looks like a relatively straightforward issue.
